

server:
  port: 8102

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: false
  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/